name: Unity CI

on:
  pull_request:
    branches:
      - main 
  push:
    branches:
      - main 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install libxml2-utils
        run: sudo apt-get install libxml2-utils
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache Library 
        uses: actions/cache@v3
        with:
          path: Library
          key: ${{ runner.os }}-unity-library-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            ${{ runner.os }}-unity-library-
      - name: Run Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport'
          coverageResultsPath: 'CodeCoverage'
          failOnCoverage: 75 
      - name: Print Working Directory
        run: pwd
      - name: List Files
        run: ls -l
      - name: List Files
        run: ls -l CodeCoverage
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3
        with:
          files: CodeCoverage/Report.xml 
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: CodeCoverage/TestResults.xml
      - name: Check Code Coverage
        run: |
          coverage=$(xmllint --xpath '//coverage/@line-rate' CodeCoverage/Report.xml)
          echo "Coverage: $coverage"
          # Add your logic here to compare $coverage with your threshold
